src/components/FileList.tsx, src/components/file-list/FileListCrumbs.tsx, src/hooks/useFileList.tsx, style/base.css
- Mimicking the JupyterLab interface, double-clicking on a directory navigates into the directory. Single-clicking just checks/unchecks the directory.
- Includes breadcrumbs at the top of the file list to navigate back to higher directory levels.
Note that no functionality exists when double-clicking on a file. This will be addressed through issue #7.
=> Feat: adds ability to navigate through user's working directory

.github/workflows/build.yml, pixi.lock, pyproject.toml, ui-tests/tests/fileglancer.spec.ts
pydantic is used by the filestore. it is installed in the pixi environment through copier, but it does not get automatically installed in the github action test environment, so we must make that explicit
=> fix: adds pydantic as a test depedency

package.json, src/App.tsx, src/components/TestComponent.tsx, tsconfig.json, tsconfig.test.json, yarn.lock
@krokicki @neomorphic This PR adds `react`, `react-dom`, and `react-router` as dependencies in `package.json`. Then, in `src/App.tsx`, I set up a very simple `BrowserRouter` for now, just to demo the routing.
Finally, unrelated to the above, I removed the `skipLibCheck:true` flag from `tsconfig.json` and `tsconfig.test.json`, since this was resolved by pinning a `jest` dependency in the `resolutions` section of `package.json`. See further conversation [here](https://github.com/JaneliaSciComp/fileglancer/pull/9#issuecomment-2659833084).
=> Feat: enable routing in widget via react-router

README.md, fileglancer/__init__.py, fileglancer/handlers.py, fileglancer/tests/test_handlers.py, src/index.ts
This PR adds a server handler for retrieving file share paths from the new [central server](https://github.com/JaneliaSciComp/fileglancer-central). I added docs in the README to describe how to configure it. 
@neomorphic @allison-truhlar @StephanPreibisch
=> Proxy API for file share paths

fileglancer/handlers.py, fileglancer/paths.py, fileglancer/tests/test_handlers.py, fileglancer/tests/test_mock_server.py, pixi.lock, pyproject.toml, src/handler.ts, src/index.ts
I modified the REST API for file access in several ways:
* Added prefix "api" to separate the API from the eventual /fileglancer route that will serve the webapp.
* The path in the URL is now the canonical file share path
* The subpath is now given by a "subpath" query parameter
@allison-truhlar @neomorphic @StephanPreibisch 
For example, you can fetch list of configured file share paths: 
**/api/fileglancer/file-share-paths**
Without a central server, this returns only the "local" path, which is the current directory:
```
[
{
"zone": "Local",
"canonical_path": "/local",
"group": "local",
"storage": "home",
"linux_path": "/Users/rokickik/dev/fileglancer"
}
]
```
Take the canonical_path `/local` and list its contents:
**/api/fileglancer/files/local**
```
{
"files": [
{
"name": …
```
=> API for browsing file shares

pixi.lock, pyproject.toml
- Added "linux-64" to platforms.
- Also had to downgrade the nodejs version as 22.13.0 is not available
for linux.
=> chore: Updates pyproject.toml to build on linux-64

fileglancer/__init__.py, fileglancer/app.py, fileglancer/handlers.py
Initialization of settings and handlers has been moved from the __init__
and handlers files into the app.py file to centralize configuration.
Adds the '/fg' url to the server, which will be the future home of the
SPA version of the fileglancer UI.
Adds a StaticHandler to serve up static content. This will be used by the
UI when it is compiled as a stand alone single page application.
Adds a VersionHandler to serve up the extension version number, which is
helpful when debugging during deployment.
@krokicki  @allison-truhlar
=> refactor: Converts backend extension to an ExtensionApp class

.github/workflows/build.yml, src/components/ui/FileListCrumbs.tsx
A small fix I forgot to include in my file list UI improvement PR last week. The breadcrumbs now correctly include the file zone name as a breadcrumb link in addition to the file path segment links. Further, following Starfish, the squares icon no longer functions as the link for the file zone.
=> Fix breadcrumbs

src/components/ui/FileList.tsx, src/contexts/PreferencesContext.tsx, src/utils.ts
This PR addresses the issues flagged by @krokicki in my last PR. Some changes were informed by discussion with @neomorphic: 
1. [Comment](https://github.com/JaneliaSciComp/fileglancer/pull/39#discussion_r2065314761); commit 92858e5f3d7287843140e8aa74d80e09dbac579f: changes `sendPutRequest` and `updatePreferences` function to use generic type variables
2. [Comment](https://github.com/JaneliaSciComp/fileglancer/pull/39#discussion_r2065338406); commit e57a605e4f1d2d6f9058b715696f92403cd29315: changes the initial useEffect to load preferences into four separate useEffects, rather than using `Promise.allSettled`. Also refactors the four useEffects to all use a common function, `fetchPreferences`, which makes use of a generic type variable.
3. …
=> Code fixes

.gitignore, src/components/Preferences.tsx, src/components/ui/FileBrowser/Crumbs.tsx, src/components/ui/FileBrowser/Dialogs/ChangePermissions.tsx, src/components/ui/FileBrowser/Dialogs/Delete.tsx, src/components/ui/FileBrowser/Dialogs/NewFolderDialog.tsx, src/components/ui/FileBrowser/Dialogs/RenameDialog.tsx, src/components/ui/FileBrowser/FileRow.tsx, src/components/ui/FileBrowser/Toolbar.tsx, src/components/ui/Navbar.tsx, src/components/ui/PropertiesDrawer/PermissionsTable.tsx, src/components/ui/PropertiesDrawer/PropertiesDrawer.tsx, src/components/ui/Sidebar/FavoritesBrowser.tsx, src/components/ui/Sidebar/FileSharePath.tsx, src/components/ui/Sidebar/Sidebar.tsx, src/components/ui/Sidebar/Zone.tsx, src/components/ui/Sidebar/ZonesBrowser.tsx, src/index.css, tailwind.config.js
In this PR, I add a custom media query for short screens and then apply styles to get extra vertical space in the sidebar. 
It saves enough space to make the scroll in the favorites and zone browser still usable at the height at which the Starfish zone browser is no longer usable (around 290px).
Fileglancer at 284px screen height:
Starfish at 284px screen height:
=> Fix sidebar scroll

pyproject.toml
Without this, the ui directory is not packaged with the dist and doesn't
show up when installed in a production setting.
=> chore: Adds ui directory to dist artifacts.

src/components/ui/FileBrowser/ContextMenu.tsx, src/components/ui/FileBrowser/Dialogs/Delete.tsx, src/components/ui/FileBrowser/Toolbar.tsx, src/components/ui/Sidebar/FavoritesBrowser.tsx, src/components/ui/Sidebar/Folder.tsx, src/components/ui/Sidebar/MissingFolderFavoriteDialog.tsx, src/components/ui/Sidebar/Zone.tsx, src/contexts/PreferencesContext.tsx, src/hooks/useNewFolderDialog.ts
Completes final task on this [clickup ticket](https://app.clickup.com/t/86a8exxrw); also adds a "refresh" button to the file browser toolbar, which was discussed but I don't think I recorded it in a ticket.
You can test the missing folder favorite dialog:
1. Right-click on a folder (either a test one or one you don't mind deleting) to use the context menu add it to favorites 
2. Delete the folder (can also be done from the Fileglancer context menu)
3. Click on the folder in the favorites browser - this brings up the dialog indicating the folder is missing and asking if you want to delete it from your favorites
=> Adds missing folder favorite dialog and a refresh btn

README.md, fileglancer/app.py, fileglancer/paths.py
This removes Dev Mode™ which we don't need because we can configure static local paths in fileglancer-central.
@allison-truhlar @neomorphic
=> Remove Dev Mode

fileglancer/handlers.py
This function has been replaced by the `initialize_handlers` function in app.py
@krokicki
=> fix: removes setup_handlers function

fileglancer/handlers.py, fileglancer/proxiedpath.py, fileglancer/tests/test_proxiedpath.py, src/components/ui/Dialogs/SharingDialog.tsx, src/contexts/ProxiedPathContext.tsx
This leverages the newly extended proxy path API which is implemented in [ fileglancer-central PR#15](https://github.com/JaneliaSciComp/fileglancer-central/pull/15). 
These two PRs should be merged at the same time, and will require everyone to delete their `fileglancer.db`, because the database is changing. 
@StephanPreibisch
=> Use new proxied path API

fileglancer/app.py, fileglancer/handlers.py, fileglancer/proxiedpath.py, fileglancer/tests/test_localfilesharepaths.py, fileglancer/tests/test_proxiedpath.py, src/__tests__/pathHandling.test.ts, src/components/ui/Dialogs/SharingDialog.tsx, src/components/ui/FileBrowser/Crumbs.tsx, src/components/ui/Sidebar/Folder.tsx, src/contexts/FileBrowserContext.tsx, src/contexts/ProxiedPathContext.tsx, src/hooks/useDeleteDialog.ts, src/hooks/useNewFolderDialog.ts, src/hooks/usePermissionsDialog.ts, src/hooks/useRenameDialog.ts, src/omezarr-helper.ts, src/utils/index.ts, src/utils/pathHandling.ts
As discussed, I moved the file content retrieval to a new endpoint at `/api/fileglancer/content/`, and changed `/api/fileglancer/files/` to always return metadata about the requested path. 
When the requested subpath is a directory you get:
```
{
info:{...}, 
files:[]
}
```
When it's a file, you just get the `info`. 
I also deleted some unused code (CORS, etc.) and moved some things around to clean up the ordering of methods (this unfortunately results in a messy diff). 
@StephanPreibisch @neomorphic
=> Refactor file API

.env.example, fileglancer/proxiedpath.py, fileglancer/uimodels.py, src/__tests__/pathHandling.test.ts, src/components/ui/Shared/ProxiedPathRow.tsx, src/contexts/ProxiedPathContext.tsx, src/utils/index.ts, src/utils/pathHandling.ts
Since [fileglancer-central#17](https://github.com/JaneliaSciComp/fileglancer-central/pull/17) is now returning a URL with each proxied path, we can use that and don't need to construct it in the client. 
@StephanPreibisch @neomorphic
=> Use external URL from ProxiedPath

src/components/ui/Shared/ProxiedPathRow.tsx, src/contexts/FileBrowserContext.tsx
This PR adds a way to navigate from each shared link (proxied path) to the file browser. 
@neomorphic @allison-truhlar @StephanPreibisch
=> Link from Shared to Browse

src/__tests__/pathHandling.test.ts, src/components/Browse.tsx, src/contexts/ProxiedPathContext.tsx, src/hooks/useProfile.ts, src/hooks/useSearchFilter.ts, src/utils/pathHandling.ts
ClickUp id: #86a92e9y4
This PR adds missing useEffect dependencies, as caught by the eslint plugin for React hooks. Note: I did not fix the missing dependeinces in `usePropertiesTarget`, as this hook is deleted in another PR (#96). 
I also removed unused imports in several files. I did not remove unused icon imports, as this is fixed in another PR (#94).
@krokicki @neomorphic
=> Fix - missing useEffect dependencies

eslint.config.mjs, src/components/ui/FileBrowser/Toolbar.tsx, src/contexts/FileBrowserContext.tsx, src/contexts/ProxiedPathContext.tsx, src/hooks/useDeleteDialog.ts, src/hooks/useNewFolderDialog.ts, src/hooks/usePermissionsDialog.ts, src/hooks/useRenameDialog.ts
This PR refactors the file browser hooks such that all state is grouped into one object. This makes downstream updates atomic, and fixes stale data issues. For the time being, I have preserved the individual states which are shared with many downstream clients. I didn't update all those locations to minimize merge conflicts. They can be easily updated at any time in the future to use the new unified state. 
During the course of refactoring I also addressed some other minor issues in the same code:
* Optimized number of fetches - since every fetch includes both info and files, each update only requires a single fetch (except when a file is provided in the URL and we have to navigate upwards, but this should be very rare). 
* Consolidated refreshes - I created a refreshFiles method which …
=> Unified file browser state

src/App.tsx, src/components/Browse.tsx, src/layouts/BrowseLayout.tsx, src/layouts/OtherPagesLayout.tsx
Click up id: 86aaau0x6
This PR:
- Adds a layout for all pages other than Browse that allows y-scrolling when there is overflow. 
- Fixes y-scrolling the Browse page for the case of short screens and no file list (which already can scroll vertically), only the dashboard
@krokicki @neomorphic
=> Fix: y-scrolling on all pages

src/components/Jobs.tsx, src/components/Links.tsx, src/contexts/FileBrowserContext.tsx, src/contexts/TicketsContext.tsx
ClickUp id: 86aaaybtb
This PR adds the propertiesTarget to the unified fileBrowserState in FileBrowserContext.tsx. Thiis fixes the problem of the properties target not being cleared if you navigate from a URL with FSP and/or file path params (e.g., `/browse/fsp_name/file_path`) to one without, (e.g. `/browse`). 
@krokicki I think this works - let me know if I should merge it or wait since we didn't plan to include it in the upcoming release.
@neomorphic
=> Correct properties target state management

src/utils/index.ts
ClickUp id: 86aaw7kfe
Uses `date.toLocaleString` instead of `date.toDateString` to return both date and time from `formatUnixTimestamp`, which is used to format the file info for the file browser.
I also added options to the `date.toLocaleString` call used in `formatDateString`, which is used to format the Jobs and Data Link data, so that seconds aren't shown - I figure this level of granularity isn't necessary.
@krokicki @neomorphic
=> feat: add time to "last modified" column in file browser

src/components/Jobs.tsx, src/components/ui/Navbar/Navbar.tsx, src/components/ui/PropertiesDrawer/PropertiesDrawer.tsx
Clickup id: 86aatawrk
For clarity, this PR changes instances of "job" to "task" in the UI text. It does not change the `/jobs` route or the names of components.
@krokicki 
@neomorphic
=> content: change "job" to "task" in UI text

src/components/ui/BrowsePage/ZarrMetadataTable.tsx, src/components/ui/BrowsePage/ZarrPreview.tsx, src/hooks/useZarrMetadata.ts, src/omezarr-helper.ts
Clickup id: 86ab01anm
Refactored axes metadata into secondary table based on feedback from @mkitti .
The metadata for an OME-Zarr now looks like this:
While a bare Zarr array looks like this:
This PR also fixes a bug that was preventing the "open with" links from showing up.
@StephanPreibisch @allison-truhlar @neomorphic
=> Metadata table improvements

src/components/ui/PropertiesDrawer/PropertiesDrawer.tsx
In v0.6.0, the properties panel width is confined to the content. This causes the content to appear disconnected from the side of the window when the panel is expanded beyond the content width.
=> fix: properties panel content width expands with panel

.github/workflows/build.yml, pyproject.toml, src/components/Preferences.tsx, src/components/ui/BrowsePage/ZarrMetadataTable.tsx, src/contexts/PreferencesContext.tsx, src/hooks/useZarrMetadata.ts, src/omezarr-helper.ts
Clickup ids: 86abk3vnm and 86abn3x6p
When Neuroglancer state generation is disabled, this now generates the same state that you would get if you pasted the URL directly into Neuroglancer.
In addition, we now implement a sampling step to classify the image type automatically. It randomly samples a subset of voxels from the volume and compute the ratio of unique intensity values to the total number of samples. If this ratio exceeds a predefined threshold (currently 0.1%), infer that the dataset represents a segmentation volume rather than a natural image. In such cases, we automatically configure Neuroglancer with the "segmentation" layer setting. 
@StephanPreibisch @vaxenburg @allison-truhlar @neomorphic
=> Neuroglancer state generation improvements

src/components/ui/widgets/Loaders.tsx, tailwind.config.js
Clickup id: 86abm3ur5
This PR addresses the issue of the skeleton loader flashing briefly in the file browser. It adds another animation that makes elements transition almost immediately from 0 to 1 opacity and a utility that sets a delay to animations. Then in the outermost div of the FileRowSkeleton component, two animations are applied: animate-appear and animate-pulse. Both are delayed by 150ms (currently, this can be adjusted) so that after 150ms, the opacity changes from 0 to 1 almost immediately and then animation-pulse takes over.
https://github.com/user-attachments/assets/d7469bcf-37cf-4a7e-b104-83e5400071e8
=> style: delay file browser loader appearance to avoid flash

src/__tests__/componentTests/ChangePermissions.test.tsx, src/__tests__/componentTests/ConvertFile.test.tsx, src/__tests__/componentTests/DataLink.test.tsx, src/__tests__/componentTests/DeleteDialog.test.tsx, src/__tests__/setup.ts, src/contexts/FileBrowserContext.tsx, src/utils/errorHandling.ts
Clickup id: 86abrcxqh
The body of the response was already getting consumed at the top of the `fetchFileInfo()` method, to provide info about the owner if there was a permissions error. Therefore, the error handling utility method `toHttpError()` couldn't consume it again when a non-permissions error was thrown to it. Now `fetchFileInfo()` uses the response body to construct a new `Error` directly, which is then displayed in the UI.
=> bug: response body already consumed

src/utils/index.ts
clickup id: [86abdmqxu](https://app.clickup.com/t/86abdmqxu)
To prevent the site from exhibiting abnormal behavior when a users session expires, I added  a`checkSessionValidity` function. The reason I had to add this function is because there are some API end points that return a 403 even when the session is still valid. To prevent logging a user out from a valid 403, the `checkSessionValidity` function makes an additional request to the `/api/fileglancer/profile` endpoint, which should always return a 200 OK response if the users session is valid. If that request returns a 403 response, then the user is redirected to the logout url and is then asked to log back in again. One can test this by modifying or deleting the `jupyterhub-session-id` cookie and then navigating to another page on …
=> fix: Adds Auto logout when a users session expires

fileglancer/handlers.py, src/components/ui/BrowsePage/NewFolderButton.tsx, src/contexts/ProxiedPathContext.tsx, src/hooks/useNewFolderDialog.ts
clickup id: [86a8mfd0r](https://app.clickup.com/t/86a8mfd0r)
Adds client side validation for empty submissions and for submissions of
folders that already exist. The client side validation provides faster
feedback, than a server round trip, but it doesn't prevent the case
where someone else creates a new directory with the same name as the one
you chose, between your submission and the initial browser page load.
@krokicki
=> fix: Adds validation of new folder submissions

src/components/ui/Navbar/ProfileMenu.tsx
Clickup id: 86ac29c1x
This PR increases the z-index of the content of the profile menu. The content is now correctly rendered on top of the properties panel content, and content on other pages.
=> fix: profile menu rendered under properties panel content

src/components/Help.tsx
Clickup id: 86ac70qk8 and 86ac7n307
For now, the link is to janeliascicomp.github.io/fileglancer-user-docs. 
I accidentally pushed the commit to this branch to "spruce up" the help page. Instead of being in a list in a single card, the help links are now in four separate cards.
=> feat: add link to user manual on help page; update help page layout

src/components/Browse.tsx, src/components/ui/BrowsePage/Dashboard/FgDashboardCard.tsx, src/components/ui/BrowsePage/NavigateInput.tsx, src/components/ui/Sidebar/FileSharePath.tsx, src/components/ui/Sidebar/Folder.tsx
Clickup ids: 86abrcz49 and 86ac7n65u
This PR makes the font of the full paths on the two dashboard cards lighter until hovered over. It also makes the dashboard card layout responsive.
=> style: make full paths on dashboard cards lighter; make dashboard layout responsive

README.md, src/components/ui/PropertiesDrawer/PropertiesDrawer.tsx, src/components/ui/Table/jobsColumns.tsx, src/components/ui/widgets/FgLink.tsx, src/constants/layoutConstants.ts, src/contexts/PreferencesContext.tsx, src/hooks/useLayoutPrefs.ts
Clickup id: 86aabdjht
@krokicki 
This PR ensures that the Properties panel is automatically open to the "Convert" tab when navigating to a path in the file browser from the jobs page.
* A new method `setLayoutWithPropertiesOpen` is added to `PreferencesContext`, allowing components to programmatically update the layout to open the properties drawer (with or without the sidebar) and persist this state.
* Layout constants (such as panel configurations and default layouts) are centralized in `src/constants/layoutConstants.ts` for consistency and maintainability between the `useLayoutPrefs` hook and `PreferencesContext`. 
* The file path link in the jobs table now uses a custom click handler to update the layout using `setLayoutWithPropertiesOpen`.
* When navigating from the jobs table to a …
=> feat: open properties panel and convert tab when navigating from jobs page
